spring:
    application:
        name: chatting
    datasource:
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_URL}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        generate-ddl: true
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
                    max-wait: -1ms
jwt:
    secret: ${JWT_SECRET}
    access-expiration-minutes: 30 # 30 minutes
    refresh-expiration-minutes: 43200 # 30 days
    token-prefix: Bearer 
    header-string: Authorization
    cookie-string: refreshToken
server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:app.p12
        key-store-type: PKCS12
        key-store-password: changeit
