FROM node:24-alpine AS build
WORKDIR /app
copy package*.json ./
RUN npm install
COPY ./src ./src
COPY ./public ./public
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]